name: Check Mirror Token

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check Secret
        run: |
          if [ -z "${{ secrets.MIRROR_TOKEN }}" ]; then
            echo "TOKEN IS EMPTY"
            exit 1
          else
            echo "TOKEN EXISTS"
          fi

      - name: Test GitHub Access
        run: |
          git ls-remote https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/JohnKhoo-Work/engtek-chatbot-RAG.git

      - name: Create Mirror Remote
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/JohnKhoo-Work/engtek-chatbot-RAG.git

      - name: Test Push Authentication
        run: |
          git ls-remote mirror

      - name: Debug Remote
        run: |
          git remote -v
          
      - name: Show Git Config
        run: |
          git config --list
    
      - name: Push to mirror
        run: |
          git push https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/JohnKhoo-Work/engtek-chatbot-RAG.git --all
          git push https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/JohnKhoo-Work/engtek-chatbot-RAG.git --tags
