name: Check Mirror Token

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        run: |
          if [ -z "${{ secrets.MIRROR_TOKEN }}" ]; then
            echo "TOKEN IS EMPTY"
            exit 1
          else
            echo "TOKEN EXISTS"
          fi

      - name: Test GitHub Access
        run: |
          git ls-remote https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/JohnKhoo-Work/engtek-chatbot-RAG.git

      - name: Debug Remote
        run: |
          git remote -v
    
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/JohnKhoo-Work/engtek-chatbot-RAG.git
          git push mirror --all
          git push mirror --tags
